export const bibleVerses = [
  { quote: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", author: "John 3:16" },
  { quote: "In the beginning was the Word, and the Word was with God, and the Word was God.", author: "John 1:1" },
  { quote: "Jesus answered, \"I am the way and the truth and the life. No one comes to the Father except through me.\"", author: "John 14:6" },
  { quote: "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit", author: "Matthew 28:19" },
  { quote: "For all have sinned and fall short of the glory of God", author: "Romans 3:23" },
  { quote: "For it is by grace you have been saved, through faith – and this is not from yourselves, it is the gift of God –", author: "Ephesians 2:8" },
  { quote: "In the beginning God created the heavens and the earth.", author: "Genesis 1:1" },
  { quote: "\"But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.\"", author: "Acts 1:8" },
  { quote: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness", author: "2 Timothy 3:16" },
  { quote: "If you declare with your mouth, \"Jesus is Lord,\" and believe in your heart that God raised him from the dead, you will be saved.", author: "Romans 10:9" },
  { quote: "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", author: "Romans 6:23" },
  { quote: "Peter replied, \"Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.\"", author: "Acts 2:38" },
  { quote: "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God –", author: "John 1:12" },
  { quote: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", author: "Romans 8:28" },
  { quote: "The true light that gives light to everyone was coming into the world.", author: "John 1:9" },
  { quote: "Then God said, \"Let us make human beings in our image, in our likeness, so that they may rule over the fish in the sea and the birds in the sky, over the livestock and all the wild animals, and over all the creatures that move along the ground.\"", author: "Genesis 1:26" },
  { quote: "Therefore, I urge you, brothers and sisters, in view of God's mercy, to offer your bodies as a living sacrifice, holy and pleasing to God – this is true worship.", author: "Romans 12:1" },
  { quote: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.", author: "Romans 5:8" },
  { quote: "Then Jesus came to them and said, \"All authority in heaven and on earth has been given to me.\"", author: "Matthew 28:18" },
  { quote: "Jesus replied, \"Very truly I tell you, no one can see the kingdom of God without being born again.\"", author: "John 3:3" },
  { quote: "He said to them, \"Go into all the world and preach the gospel to all creation.\"", author: "Mark 16:15" },
  { quote: "The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.", author: "John 10:10" },
  { quote: "The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth.", author: "John 1:14" },
  { quote: "\"Salvation is found in no one else, for there is no other name given under heaven by which we must be saved.\"", author: "Acts 4:12" },
  { quote: "They devoted themselves to the apostles' teaching and to fellowship, to the breaking of bread and to prayer.", author: "Acts 2:42" },
  { quote: "Now there was a Pharisee, a man named Nicodemus who was a member of the Jewish ruling council.", author: "John 3:1" },
  { quote: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness", author: "Galatians 5:22" },
  { quote: "Trust in the LORD with all your heart and lean not on your own understanding", author: "Proverbs 3:5" },
  { quote: "For I know the plans I have for you,\" declares the LORD, \"plans to prosper you and not to harm you, plans to give you hope and a future.", author: "Jeremiah 29:11" },
  { quote: "On the third day a wedding took place at Cana in Galilee. Jesus' mother was there,", author: "John 2:1" },
  { quote: "He saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit", author: "Titus 3:5" },
  { quote: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is – his good, pleasing and perfect will.", author: "Romans 12:2" },
  { quote: "\"Do not let your hearts be troubled. Trust in God; trust also in me.\"", author: "John 14:1" },
  { quote: "Now Jesus learned that the Pharisees had heard that he was gaining and baptizing more disciples than John –", author: "John 4:1" },
  { quote: "So Christ himself gave the apostles, the prophets, the evangelists, the pastors and teachers", author: "Ephesians 4:11" },
  { quote: "Therefore, just as sin entered the world through one man, and death through sin, and in this way death came to all people, because all sinned –", author: "Romans 5:12" },
  { quote: "\"Come to me, all you who are weary and burdened, and I will give you rest.\"", author: "Matthew 11:28" },
  { quote: "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ", author: "Romans 5:1" },
  { quote: "So God created human beings in his own image, in the image of God he created them; male and female he created them.", author: "Genesis 1:27" },
  { quote: "I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes: first to the Jew, then to the Gentile.", author: "Romans 1:16" },
  { quote: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.", author: "1 John 1:9" },
  { quote: "When the day of Pentecost came, they were all together in one place.", author: "Acts 2:1" },
  { quote: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", author: "2 Corinthians 5:17" },
  { quote: "Now faith is being sure of what we hope for and certain of what we do not see.", author: "Hebrews 11:1" },
  { quote: "Do your best to present yourself to God as one approved, a worker who does not need to be ashamed and who correctly handles the word of truth.", author: "2 Timothy 2:15" },
  { quote: "Therefore, there is now no condemnation for those who are in Christ Jesus", author: "Romans 8:1" },
  { quote: "For, \"Everyone who calls on the name of the Lord will be saved.\"", author: "Romans 10:13" },
  { quote: "\"Then you will know the truth, and the truth will set you free.\"", author: "John 8:32" },
  { quote: "For to us a child is born, to us a son is given, and the government will be on his shoulders. And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.", author: "Isaiah 9:6" },
  { quote: "\"If you love me, keep my commands.\"", author: "John 14:15" },
  { quote: "Hear, O Israel: The LORD our God, the LORD is one.", author: "Deuteronomy 6:4" },
  { quote: "\"A new command I give you: Love one another. As I have loved you, so you must love one another.\"", author: "John 13:34" },
  { quote: "\"God is spirit, and his worshipers must worship in the Spirit and in truth.\"", author: "John 4:24" },
  { quote: "I can do all this through him who gives me strength.", author: "Philippians 4:13" },
  { quote: "As for you, you were dead in your transgressions and sins", author: "Ephesians 2:1" },
  { quote: "And I will ask the Father, and he will give you another advocate to help you and be with you forever –", author: "John 14:16" },
  { quote: "Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.", author: "Genesis 1:2" },
  { quote: "For the word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart.", author: "Hebrews 4:12" },
  { quote: "Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective.", author: "James 5:16" },
  { quote: "Therefore the Lord himself will give you a sign: The virgin will conceive and give birth to a son, and will call him Immanuel.", author: "Isaiah 7:14" },
  { quote: "He came as a witness to testify concerning that light, so that through him all might believe.", author: "John 1:7" },
  { quote: "Jesus answered, \"Very truly I tell you, no one can enter the kingdom of God without being born of water and the Spirit.\"", author: "John 3:5" },
  { quote: "In your relationships with one another, have the same attitude of mind Christ Jesus had:", author: "Philippians 2:5" },
  { quote: "The next day John saw Jesus coming toward him and said, \"Look, the Lamb of God, who takes away the sin of the world!\"", author: "John 1:29" },
  { quote: "The wrath of God is being revealed from heaven against all the godlessness and wickedness of human beings who suppress the truth by their wickedness", author: "Romans 1:18" },
  { quote: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", author: "Philippians 4:6" },
  { quote: "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us,", author: "Hebrews 12:1" },
  { quote: "Through him all things were made; without him nothing was made that has been made.", author: "John 1:3" },
  { quote: "And I tell you that you are Peter, and on this rock I will build my church, and the gates of death will not overcome it.", author: "Matthew 16:18" },
  { quote: "Now the Berean Jews were of more noble character than those in Thessalonica, for they received the message with great eagerness and examined the Scriptures every day to see if what Paul said was true.", author: "Acts 17:11" },
  { quote: "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.", author: "Galatians 2:20" },
  { quote: "\"When the Son of Man comes in his glory, and all the angels with him, he will sit on his glorious throne.\"", author: "Matthew 25:31" },
  { quote: "\"Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfill them.\"", author: "Matthew 5:17" },
  { quote: "Consequently, faith comes from hearing the message, and the message is heard through the word about Christ.", author: "Romans 10:17" },
  { quote: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", author: "Matthew 6:33" },
  { quote: "\"The Spirit of the Lord is on me, because he has anointed me to proclaim good news to the poor. He has sent me to proclaim freedom for the prisoners and recovery of sight for the blind, to set the oppressed free,\"", author: "Luke 4:18" },
  { quote: "But when he, the Spirit of truth, comes, he will guide you into all the truth. He will not speak on his own; he will speak only what he hears, and he will tell you what is yet to come.", author: "John 16:13" },
  { quote: "Keep watch over yourselves and all the flock of which the Holy Spirit has made you overseers. Be shepherds of the church of God, which he bought with his own blood.", author: "Acts 20:28" },
  { quote: "For the grace of God has appeared that offers salvation to all people.", author: "Titus 2:11" },
  { quote: "You belong to your father, the devil, and you want to carry out your father's desires. He was a murderer from the beginning, not holding to the truth, for there is no truth in him. When he lies, he speaks his native language, for he is a liar and the father of lies.", author: "John 8:44" },
  { quote: "Finally, be strong in the Lord and in his mighty power.", author: "Ephesians 6:10" },
  { quote: "Let everyone be subject to the governing authorities, for there is no authority except that which God has established. The authorities that exist have been established by God.", author: "Romans 13:1" },
  { quote: "So he made a whip out of cords, and drove all from the temple courts, both sheep and cattle; he scattered the coins of the money changers and overturned their tables.", author: "John 2:15" },
  { quote: "Whoever believes and is baptized will be saved, but whoever does not believe will be condemned.", author: "Mark 16:16" },
  { quote: "As it is written: \"There is no one righteous, not even one;\"", author: "Romans 3:10" },
  { quote: "\"And I will put enmity between you and the woman, and between your offspring and hers; he will crush your head, and you will strike his heel.\"", author: "Genesis 3:15" },
  { quote: "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.", author: "Hebrews 11:6" },
  { quote: "But the Advocate, the Holy Spirit, whom the Father will send in my name, will teach you all things and will remind you of everything I have said to you.", author: "John 14:26" },
  { quote: "\"Very truly I tell you, whoever hears my word and believes him who sent me has eternal life and will not be judged but has crossed over from death to life.\"", author: "John 5:24" },
  { quote: "\"And afterward, I will pour out my Spirit on all people. Your sons and daughters will prophesy, your old men will dream dreams, your young men will see visions.\"", author: "Joel 2:28" },
  { quote: "Then God said, \"Let the land produce vegetation: seed-bearing plants and trees on the land that bear fruit with seed in it, according to their various kinds.\" And it was so.", author: "Genesis 1:11" },
  { quote: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds", author: "James 1:2" },
  { quote: "The Son is the image of the invisible God, the firstborn over all creation.", author: "Colossians 1:15" },
  { quote: "Jesus replied: \"Love the Lord your God with all your heart and with all your soul and with all your mind.'\"", author: "Matthew 22:37" },
  { quote: "While we wait for the blessed hope – the appearing of the glory of our great God and Savior, Jesus Christ", author: "Titus 2:13" },
  { quote: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable – if anything is excellent or praiseworthy – think about such things.", author: "Philippians 4:8" },
  { quote: "After he said this, he was taken up before their very eyes, and a cloud hid him from their sight.", author: "Acts 1:9" },
  { quote: "When a Samaritan woman came to draw water, Jesus said to her, \"Will you give me a drink?\"", author: "John 4:7" },
  { quote: "He has shown all you people what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.", author: "Micah 6:8" },
  { quote: "Sanctify them by the truth; your word is truth.", author: "John 17:17" },
  { quote: "\"Do not have sexual relations with a man as one does with a woman; that is detestable.\"", author: "Leviticus 18:22" },
  { quote: "On the first day of the week we came together to break bread. Paul spoke to the people and, because he intended to leave the next day, kept on talking until midnight.", author: "Acts 20:7" },
  { quote: "They replied, \"Believe in the Lord Jesus, and you will be saved – you and your household.\"", author: "Acts 16:31" },
  { quote: "Jesus said to her, \"I am the resurrection and the life. Anyone who believes in me will live, even though they die;\"", author: "John 11:25" },
  { quote: "\"Very truly I tell you,\" Jesus answered, \"before Abraham was born, I am!\"", author: "John 8:58" },
  { quote: "All of them were filled with the Holy Spirit and began to speak in other tongues as the Spirit enabled them.", author: "Acts 2:4" },
  { quote: "\"I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.\"", author: "John 15:5" },
  { quote: "Those who accepted his message were baptized, and about three thousand were added to their number that day.", author: "Acts 2:41" },
  { quote: "Start children off on the way they should go, and even when they are old they will not turn from it.", author: "Proverbs 22:6" },
  { quote: "Now the serpent was more crafty than any of the wild animals the LORD God had made. He said to the woman, \"Did God really say, 'You must not eat from any tree in the garden'?\"", author: "Genesis 3:1" },
  { quote: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.", author: "James 1:5" },
  { quote: "In the past God spoke to our ancestors through the prophets at many times and in various ways", author: "Hebrews 1:1" },
  { quote: "Because of the truth, which lives in us and will be with us forever:", author: "2 John 1:2" },
  { quote: "Now this is eternal life: that they know you, the only true God, and Jesus Christ, whom you have sent.", author: "John 17:3" },
  { quote: "\"There was a rich man who was dressed in purple and fine linen and lived in luxury every day.\"", author: "Luke 16:19" },
  { quote: "\"Sir,\" the invalid replied, \"I have no one to help me into the pool when the water is stirred. While I am trying to get in, someone else goes down ahead of me.\"", author: "John 5:7" },
  { quote: "To the Jews who had believed him, Jesus said, \"If you hold to my teaching, you are really my disciples.\"", author: "John 8:31" },
  { quote: "So that you may know the certainty of the things you have been taught.", author: "Luke 1:4" },
  { quote: "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with them, and they with me.", author: "Revelation 3:20" },
  { quote: "Now that you have tasted that the Lord is good.", author: "1 Peter 2:3" },
  { quote: "\"I and the Father are one.\"", author: "John 10:30" },
  { quote: "But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have. But do this with gentleness and respect", author: "1 Peter 3:15" },
  { quote: "\"Not everyone who says to me, 'Lord, Lord,' will enter the kingdom of heaven, but only those who do the will of my Father who is in heaven.\"", author: "Matthew 7:21" },
  { quote: "Whoever believes in him is not condemned, but whoever does not believe stands condemned already because they have not believed in the name of God's one and only Son.", author: "John 3:18" },
  { quote: "The LORD had said to Abram, \"Go from your country, your people and your father's household to the land I will show you.\"", author: "Genesis 12:1" },
  { quote: "\"The wind blows wherever it pleases. You hear its sound, but you cannot tell where it comes from or where it is going. So it is with everyone born of the Spirit.\"", author: "John 3:8" },
  { quote: "\"I am the true vine, and my Father is the gardener.\"", author: "John 15:1" },
  { quote: "Then the LORD God formed a man from the dust of the ground and breathed into his nostrils the breath of life, and the man became a living being.", author: "Genesis 2:7" },
  { quote: "And God said, \"Let there be light,\" and there was light.", author: "Genesis 1:3" },
  { quote: "When Jesus spoke again to the people, he said, \"I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.\"", author: "John 8:12" },
  { quote: "But you are a chosen people, a royal priesthood, a holy nation, God's special possession, that you may declare the praises of him who called you out of darkness into his wonderful light.", author: "1 Peter 2:9" },
  { quote: "In the sixth month of Elizabeth's pregnancy, God sent the angel Gabriel to Nazareth, a town in Galilee", author: "Luke 1:26" },
  { quote: "Just as people are destined to die once, and after that to face judgment", author: "Hebrews 9:27" },
  { quote: "He came to Jesus at night and said, \"Rabbi, we know that you are a teacher who has come from God. For no one could perform the signs you are doing if God were not with him.\"", author: "John 3:2" },
  { quote: "\"You are the light of the world. A city on a hill cannot be hidden.\"", author: "Matthew 5:14" },
  { quote: "\"God said to Moses, \"I AM WHO I AM. This is what you are to say to the Israelites: 'I AM has sent me to you.\"\"", author: "Exodus 3:14" },
  { quote: "Or do you not know that wrongdoers will not inherit the kingdom of God? Do not be deceived: Neither the sexually immoral nor idolaters nor adulterers nor male prostitutes nor practicing homosexuals", author: "1 Corinthians 6:9" },
  { quote: "On one occasion an expert in the law stood up to test Jesus. \"Teacher,\" he asked, \"what must I do to inherit eternal life?\"", author: "Luke 10:25" },
  { quote: "\"Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.\"", author: "Matthew 7:7" },
  { quote: "He himself was not the light; he came only as a witness to the light.", author: "John 1:8" },
  { quote: "Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ.", author: "Ephesians 1:3" },
  { quote: "This is how the birth of Jesus the Messiah came about: His mother Mary was pledged to be married to Joseph, but before they came together, she was found to be pregnant through the Holy Spirit.", author: "Matthew 1:18" },
  { quote: "For since the creation of the world God's invisible qualities – his eternal power and divine nature – have been clearly seen, being understood from what has been made, so that people are without excuse.", author: "Romans 1:20" },
  { quote: "At this, those who heard began to go away one at a time, the older ones first, until only Jesus was left, with the woman still standing there.", author: "John 8:9" },
  { quote: "The light shines in the darkness, and the darkness has not overcome it.", author: "John 1:5" },
  { quote: "Brothers and sisters, we do not want you to be uninformed about those who sleep in death, so that you do not grieve like the rest, who have no hope.", author: "1 Thessalonians 4:13" },
  { quote: "Keep your lives free from the love of money and be content with what you have, because God has said, \"Never will I leave you; never will I forsake you.\"", author: "Hebrews 13:5" },
  { quote: "Dear friends, do not believe every spirit, but test the spirits to see whether they are from God, because many false prophets have gone out into the world.", author: "1 John 4:1" },
  { quote: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows.", author: "James 1:17" },
  { quote: "\"Do not store up for yourselves treasures on earth, where moth and rust destroy, and where thieves break in and steal.\"", author: "Matthew 6:19" },
  { quote: "The Spirit of the Sovereign LORD is on me, because the LORD has anointed me to proclaim good news to the poor. He has sent me to bind up the brokenhearted, to proclaim freedom for the captives and release from darkness for the prisoners,", author: "Isaiah 61:1" },
  { quote: "There is neither Jew nor Gentile, neither slave nor free, neither male nor female, for you are all one in Christ Jesus.", author: "Galatians 3:28" },
  { quote: "The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you, not wanting anyone to perish, but everyone to come to repentance.", author: "2 Peter 3:9" },
  { quote: "\"Men of Galilee,\" they said, \"why do you stand here looking into the sky? This same Jesus, who has been taken from you into heaven, will come back in the same way you have seen him go into heaven.\"", author: "Acts 1:11" },
  { quote: "Is anyone among you sick? Let them call the elders of the church to pray over them and anoint them with oil in the name of the Lord.", author: "James 5:14" },
  { quote: "Whoever believes in the Son has eternal life, but whoever rejects the Son will not see life, for God's wrath remains on them.", author: "John 3:36" },
  { quote: "For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.", author: "Ephesians 6:12" },
  { quote: "\"This, then, is how you should pray: \"Our Father in heaven, hallowed be your name,\"\"", author: "Matthew 6:9" },
  { quote: "Repent, then, and turn to God, so that your sins may be wiped out, that times of refreshing may come from the Lord", author: "Acts 3:19" },
  { quote: "What good is it, my brothers and sisters, if people claim to have faith but have no deeds? Can such faith save them?", author: "James 2:14" },
  { quote: "But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", author: "Isaiah 40:31" },
  { quote: "For God did not send his Son into the world to condemn the world, but to save the world through him.", author: "John 3:17" },
  { quote: "The angel answered, \"The Holy Spirit will come on you, and the power of the Most High will overshadow you. So the holy one to be born will be called the Son of God.\"", author: "Luke 1:35" },
  { quote: "God blessed them and said to them, \"Be fruitful and increase in number; fill the earth and subdue it. Rule over the fish in the sea and the birds in the sky and over every living creature that moves on the ground.\"", author: "Genesis 1:28" },
  { quote: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.", author: "Ephesians 2:10" },
  { quote: "God made him who had no sin to be sin for us, so that in him we might become the righteousness of God.", author: "2 Corinthians 5:21" },
  { quote: "What shall we say, then? Shall we go on sinning so that grace may increase?", author: "Romans 6:1" },
  { quote: "And you also were included in Christ when you heard the word of truth, the gospel of your salvation. When you believed, you were marked in him with a seal, the promised Holy Spirit", author: "Ephesians 1:13" },
  { quote: "Or don't you know that all of us who were baptized into Christ Jesus were baptized into his death?", author: "Romans 6:3" },
  { quote: "\"If a brother or sister sins, go and point out the fault, just between the two of you. If they listen to you, you have won them over.\"", author: "Matthew 18:15" },
  { quote: "They are from the world and therefore speak from the viewpoint of the world, and the world listens to them.", author: "1 John 4:5" },
  { quote: "In those days Caesar Augustus issued a decree that a census should be taken of the entire Roman world.", author: "Luke 2:1" },
  { quote: "Religion that God our Father accepts as pure and faultless is this: to look after orphans and widows in their distress and to keep oneself from being polluted by the world.", author: "James 1:27" },
  { quote: "\"I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.\"", author: "John 16:33" },
  { quote: "\"Do not be amazed at this, for a time is coming when all who are in their graves will hear his voice\"", author: "John 5:28" },
  { quote: "You study the Scriptures diligently because you think that in them you possess eternal life. These are the very Scriptures that testify about me,", author: "John 5:39" },
  { quote: "Likewise, teach the older women to be reverent in the way they live, not to be slanderers or addicted to much wine, but to teach what is good.", author: "Titus 2:3" },
  { quote: "Yet a time is coming and has now come when the true worshipers will worship the Father in the Spirit and in truth, for they are the kind of worshipers the Father seeks.", author: "John 4:23" },
  { quote: "\"Do not judge, or you too will be judged.\"", author: "Matthew 7:1" },
  { quote: "For there is one God and one mediator between God and human beings, Christ Jesus, himself human", author: "1 Timothy 2:5" },
  { quote: "Then Jesus was led by the Spirit into the wilderness to be tempted by the devil.", author: "Matthew 4:1" },
  { quote: "No one has ever seen God, but the one and only Son, who is himself God and is in closest relationship with the Father, has made him known.", author: "John 1:18" },
  { quote: "As a prisoner for the Lord, then, I urge you to live a life worthy of the calling you have received.", author: "Ephesians 4:1" },
  { quote: "Some time later, Jesus went up to Jerusalem for one of the Jewish festivals.", author: "John 5:1" },
  { quote: "Do not get drunk on wine, which leads to debauchery. Instead, be filled with the Spirit", author: "Ephesians 5:18" },
  { quote: "Wives, submit yourselves to your own husbands as you do to the Lord.", author: "Ephesians 5:22" },
  { quote: "Then I saw \"a new heaven and a new earth,\" for the first heaven and the first earth had passed away, and there was no longer any sea.", author: "Revelation 21:1" },
  { quote: "\"But you, Bethlehem Ephrathah, though you are small among the clans of Judah, out of you will come for me one who will be ruler over Israel, whose origins are from of old, from ancient times.\"", author: "Micah 5:2" },
  { quote: "They will say, \"Where is this 'coming' he promised? Ever since our ancestors died, everything goes on as it has since the beginning of creation.\"", author: "2 Peter 3:4" },
  { quote: "\"No one can come to me unless the Father who sent me draws them, and I will raise them up at the last day.\"", author: "John 6:44" },
  { quote: "On the evening of that first day of the week, when the disciples were together, with the doors locked for fear of the Jewish leaders, Jesus came and stood among them and said, \"Peace be with you!\"", author: "John 20:19" },
  { quote: "Nun. Your word is a lamp to my feet and a light for my path.", author: "Psalms 119:105" },
  { quote: "The LORD God said, \"It is not good for the man to be alone. I will make a helper suitable for him.\"", author: "Genesis 2:18" },
  { quote: "But if we walk in the light, as he is in the light, we have fellowship with one another, and the blood of Jesus, his Son, purifies us from all sin.", author: "1 John 1:7" },
  { quote: "For what I received I passed on to you as of first importance: that Christ died for our sins according to the Scriptures,", author: "1 Corinthians 15:3" },
  { quote: "But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.", author: "Isaiah 53:5" },
  { quote: "In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God's grace", author: "Ephesians 1:7" },
  { quote: "Husbands, love your wives, just as Christ loved the church and gave himself up for her", author: "Ephesians 5:25" },
  { quote: "You, however, are not controlled by the sinful nature but are in the Spirit, if indeed the Spirit of God lives in you. And if anyone does not have the Spirit of Christ, they do not belong to Christ.", author: "Romans 8:9" },
  { quote: "Greater love has no one than this: to lay down one's life for one's friends.", author: "John 15:13" },
  { quote: "So I say, walk by the Spirit, and you will not gratify the desires of the sinful nature.", author: "Galatians 5:16" },
  { quote: "Just as Moses lifted up the snake in the wilderness, so the Son of Man must be lifted up", author: "John 3:14" },
  { quote: "\"How can anyone be born when they are old?\" Nicodemus asked. \"Surely they cannot enter a second time into their mother's womb to be born!\"", author: "John 3:4" },
  { quote: "Jesus continued: \"There was a man who had two sons.\"", author: "Luke 15:11" },
  { quote: "\"Enter through the narrow gate. For wide is the gate and broad is the road that leads to destruction, and many enter through it.\"", author: "Matthew 7:13" },
  { quote: "Do not merely listen to the word, and so deceive yourselves. Do what it says.", author: "James 1:22" },
  { quote: "For this reason a man will leave his father and mother and be united to his wife, and they will become one flesh.", author: "Genesis 2:24" },
  { quote: "My sheep listen to my voice; I know them, and they follow me.", author: "John 10:27" },
  { quote: "For in him all things were created: things in heaven and on earth, visible and invisible, whether thrones or powers or rulers or authorities; all things have been created through him and for him.", author: "Colossians 1:16" },
  { quote: "Since, then, you have been raised with Christ, set your hearts on things above, where Christ is seated at the right hand of God.", author: "Colossians 3:1" },
  { quote: "In the past God overlooked such ignorance, but now he commands all people everywhere to repent.", author: "Acts 17:30" },
  { quote: "But very truly I tell you, it is for your good that I am going away. Unless I go away, the Advocate will not come to you; but if I go, I will send him to you.", author: "John 16:7" },
  { quote: "For Christ also suffered once for sins, the righteous for the unrighteous, to bring you to God. He was put to death in the body but made alive in the Spirit.", author: "1 Peter 3:18" },
  { quote: "Not giving up meeting together, as some are in the habit of doing, but encouraging one another – and all the more as you see the Day approaching.", author: "Hebrews 10:25" },
  { quote: "And Jesus and his disciples had also been invited to the wedding.", author: "John 2:2" },
  { quote: "For everyone who asks receives; those who seek find; and to those who knock, the door will be opened.", author: "Matthew 7:8" },
  { quote: "\"You are the salt of the earth. But if the salt loses its saltiness, how can it be made salty again? It is no longer good for anything, except to be thrown out and trampled underfoot.\"", author: "Matthew 5:13" },
  { quote: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.", author: "James 4:7" },
  { quote: "\"I am the good shepherd. The good shepherd lays down his life for the sheep.\"", author: "John 10:11" },
  { quote: "(His disciples had gone into the town to buy food.)", author: "John 4:8" },
  { quote: "\"He himself bore our sins\" in his body on the cross, so that we might die to sins and live for righteousness; \"by his wounds you have been healed.\"", author: "1 Peter 2:24" },
  { quote: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", author: "John 14:27" },
  { quote: "All whom the Father gives me will come to me, and whoever comes to me I will never drive away.", author: "John 6:37" },
  { quote: "In those days when the number of disciples was increasing, the Hellenistic Jews among them complained against the Hebraic Jews because their widows were being overlooked in the daily distribution of food.", author: "Acts 6:1" },
  { quote: "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans.", author: "Romans 8:26" },
  { quote: "Early on the first day of the week, while it was still dark, Mary Magdalene went to the tomb and saw that the stone had been removed from the entrance.", author: "John 20:1" },
  { quote: "Philip answered him, \"It would take almost a year's wages to buy enough bread for each one to have a bite!\"", author: "John 6:7" },
  { quote: "One Sabbath, when Jesus went to eat in the house of a prominent Pharisee, he was being carefully watched.", author: "Luke 14:1" },
  { quote: "For those God foreknew he also predestined to be conformed to the image of his Son, that he might be the firstborn among many brothers and sisters.", author: "Romans 8:29" },
  { quote: "Jesus gave them this answer: \"Very truly I tell you, the Son can do nothing by himself; he can do only what he sees his Father doing, because whatever the Father does the Son also does.\"", author: "John 5:19" },
  { quote: "The heart is deceitful above all things and beyond cure. Who can understand it?", author: "Jeremiah 17:9" },
  { quote: "Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God.", author: "1 John 4:7" },
  { quote: "The descendants of Jacob numbered seventy in all; Joseph was already in Egypt.", author: "Exodus 1:5" },
  { quote: "Do not love the world or anything in the world. If you love the world, love for the Father is not in you.", author: "1 John 2:15" },
  { quote: "Above all, you must understand that no prophecy of Scripture came about by the prophet's own interpretation of things.", author: "2 Peter 1:20" },
  { quote: "Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.", author: "Colossians 3:12" },
  { quote: "\"When the Advocate comes, whom I will send to you from the Father – the Spirit of truth who goes out from the Father – he will testify about me.\"", author: "John 15:26" },
  { quote: "\"My prayer is not for them alone. I pray also for those who will believe in me through their message,\"", author: "John 17:20" },
  { quote: "See what great love the Father has lavished on us, that we should be called children of God! And that is what we are! The reason the world does not know us is that it did not know him.", author: "1 John 3:1" },
  { quote: "Then Peter began to speak: \"I now realize how true it is that God does not show favoritism\"", author: "Acts 10:34" },
  { quote: "He went to Nazareth, where he had been brought up, and on the Sabbath day he went into the synagogue, as was his custom. He stood up to read", author: "Luke 4:16" },
  { quote: "After Jesus was born in Bethlehem in Judea, during the time of King Herod, Magi from the east came to Jerusalem", author: "Matthew 2:1" },
  { quote: "The reason I left you in Crete was that you might put in order what was left unfinished and appoint elders in every town, as I directed you.", author: "Titus 1:5" },
  { quote: "As soon as it was night, the believers sent Paul and Silas away to Berea. On arriving there, they went to the Jewish synagogue.", author: "Acts 17:10" },
  { quote: "Then he said to them all: \"Whoever wants to be my disciple must deny themselves and take up their cross daily and follow me.\"", author: "Luke 9:23" },
  { quote: "So in Christ Jesus you are all children of God through faith", author: "Galatians 3:26" },
  { quote: "My dear children, I write this to you so that you will not sin. But if anybody does sin, we have an advocate with the Father – Jesus Christ, the Righteous One.", author: "1 John 2:1" },
  { quote: "Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour.", author: "1 Peter 5:8" },
  { quote: "Grace and peace to you from God our Father and the Lord Jesus Christ.", author: "2 Corinthians 1:2" },
  { quote: "For there are three that testify:", author: "1 John 5:7" },
  { quote: "For we do not have a high priest who is unable to empathize with our weaknesses, but we have one who has been tempted in every way, just as we are – yet he did not sin.", author: "Hebrews 4:15" },
  { quote: "The Son is the radiance of God's glory and the exact representation of his being, sustaining all things by his powerful word. After he had provided purification for sins, he sat down at the right hand of the Majesty in heaven.", author: "Hebrews 1:3" },
  { quote: "In my former book, Theophilus, I wrote about all that Jesus began to do and to teach", author: "Acts 1:1" },
  { quote: "It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.", author: "Galatians 5:1" },
  { quote: "Jesus answered her, \"If you knew the gift of God and who it is that asks you for a drink, you would have asked him and he would have given you living water.\"", author: "John 4:10" },
  { quote: "Later Jesus found him at the temple and said to him, \"See, you are well again. Stop sinning or something worse may happen to you.\"", author: "John 5:14" },
  { quote: "And everyone went to their own town to register.", author: "Luke 2:3" },
  { quote: "How you have fallen from heaven, morning star, son of the dawn! You have been cast down to the earth, you who once laid low the nations!", author: "Isaiah 14:12" },
  { quote: "Jesus Christ is the same yesterday and today and forever.", author: "Hebrews 13:8" },
  { quote: "Have you experienced so much in vain – if it really was in vain?", author: "Galatians 3:4" },
  { quote: "Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom through psalms, hymns and songs from the Spirit, singing to God with gratitude in your hearts.", author: "Colossians 3:16" },
  { quote: "On the last and greatest day of the festival, Jesus stood and said in a loud voice, \"Let anyone who is thirsty come to me and drink.\"", author: "John 7:37" },
  { quote: "\"But if serving the LORD seems undesirable to you, then choose for yourselves this day whom you will serve, whether the gods your ancestors served beyond the Euphrates, or the gods of the Amorites, in whose land you are living. But as for me and my household, we will serve the LORD.\"", author: "Joshua 24:15" },
  { quote: "In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", author: "Matthew 5:16" },
  { quote: "For those who are led by the Spirit of God are the children of God.", author: "Romans 8:14" },
  { quote: "Then Solomon spoke to all Israel – to the commanders of thousands and commanders of hundreds, to the judges and to all the leaders in Israel, the heads of families –", author: "2 Chronicles 1:2" },
  { quote: "One day Jesus was praying in a certain place. When he finished, one of his disciples said to him, \"Lord, teach us to pray, just as John taught his disciples.\"", author: "Luke 11:1" },
  { quote: "As Jesus and his disciples were on their way, he came to a village where a woman named Martha opened her home to him.", author: "Luke 10:38" },
  { quote: "What, then, shall we say in response to these things? If God is for us, who can be against us?", author: "Romans 8:31" },
  { quote: "It was just before the Passover Festival. Jesus knew that the hour had come for him to leave this world and go to the Father. Having loved his own who were in the world, he loved them to the end.", author: "John 13:1" },
  { quote: "In him was life, and that life was the light of all people.", author: "John 1:4" },
  { quote: "Therefore, my dear friends, as you have always obeyed – not only in my presence, but now much more in my absence – continue to work out your salvation with fear and trembling", author: "Philippians 2:12" },
  { quote: "Large crowds were traveling with Jesus, and turning to them he said:", author: "Luke 14:25" },
  { quote: "Jesus replied, \"Anyone who loves me will obey my teaching. My Father will love them, and we will come to them and make our home with them.\"", author: "John 14:23" },
  { quote: "When he comes, he will prove the world to be in the wrong about sin and righteousness and judgment:", author: "John 16:8" },
  { quote: "For prophecy never had its origin in the human will, but prophets, though human, spoke from God as they were carried along by the Holy Spirit.", author: "2 Peter 1:21" },
  { quote: "If we claim to be without sin, we deceive ourselves and the truth is not in us.", author: "1 John 1:8" },
  { quote: "Then Jesus told his disciples a parable to show them that they should always pray and not give up.", author: "Luke 18:1" },
  { quote: "If you show special attention to the one wearing fine clothes and say, \"Here's a good seat for you,\" but say to the one who is poor, \"You stand there\" or \"Sit on the floor by my feet,\"", author: "James 2:3" },
  { quote: "Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.", author: "Philippians 1:6" },
  { quote: "\"Watch out for false prophets. They come to you in sheep's clothing, but inwardly they are ferocious wolves.\"", author: "Matthew 7:15" },
  { quote: "Jesus answered them, \"Destroy this temple, and I will raise it again in three days.\"", author: "John 2:19" },
  { quote: "\"Remember the Sabbath day by keeping it holy.\"", author: "Exodus 20:8" },
  { quote: "And let us consider how we may spur one another on toward love and good deeds", author: "Hebrews 10:24" },
  { quote: "Therefore if you have any encouragement from being united with Christ, if any comfort from his love, if any common sharing in the Spirit, if any tenderness and compassion", author: "Philippians 2:1" },
  { quote: "My Father's house has plenty of room; if that were not so, would I have told you that I am going there to prepare a place for you?", author: "John 14:2" },
  { quote: "Do not be deceived: God cannot be mocked. People reap what they sow.", author: "Galatians 6:7" },
  { quote: "We were therefore buried with him through baptism into death in order that, just as Christ was raised from the dead through the glory of the Father, we too may live a new life.", author: "Romans 6:4" },
  { quote: "Blessed are the merciful, for they will be shown mercy.", author: "Matthew 5:7" },
  { quote: "The acts of the sinful nature are obvious: sexual immorality, impurity and debauchery", author: "Galatians 5:19" },
  { quote: "The Jews then responded to him, \"What sign can you show us to prove your authority to do all this?\"", author: "John 2:18" },
  { quote: "Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead", author: "1 Peter 1:3" },
  { quote: "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers,", author: "Romans 8:38" },
  { quote: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", author: "1 Corinthians 13:4" },
  { quote: "Then Jesus declared, \"I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.\"", author: "John 6:35" },
  { quote: "Meanwhile, Saul was still breathing out murderous threats against the Lord's disciples. He went to the high priest", author: "Acts 9:1" },
  { quote: "Mercy, peace and love be yours in abundance.", author: "Jude 1:2" },
  { quote: "For he chose us in him before the creation of the world to be holy and blameless in his sight. In love", author: "Ephesians 1:4" },
  { quote: "When they had finished eating, Jesus said to Simon Peter, \"Simon son of John, do you love me more than these?\" \"Yes, Lord,\" he said, \"you know that I love you.\" Jesus said, \"Feed my lambs.\"", author: "John 21:15" },
  { quote: "The man who was healed had no idea who it was, for Jesus had slipped away into the crowd that was there.", author: "John 5:13" },
];